/* meese.rs UI kit — sample content (on-brand voice: sentence case, builder tone) */
(function () {
  const POSTS = [
    {
      slug: 'expo-sdk-56-real-device',
      type: 'guide',
      title: 'Getting an Expo SDK 56 app running on a real device',
      description: 'Modernizing an old app to the newest SDK turns up a few gotchas the docs never connect for you — here is the path that actually worked.',
      date: '2026-06-08', updated: '2026-06-11', readingTime: '7 min',
      topics: ['react-native', 'expo', 'mobile-dev'],
      tags: ['expo-sdk', 'android', 'eas'],
      featured: true,
    },
    {
      slug: 'expo-go-version-mismatch',
      type: 'note',
      title: 'Expo Go version mismatch is still a bad failure mode',
      description: 'The error points at the runtime when the real problem is the SDK. Two minutes of confusion that a one-line hint would fix.',
      date: '2026-06-09', readingTime: '2 min',
      topics: ['react-native', 'expo'],
      tags: ['expo-go', 'developer-experience'],
    },
    {
      slug: 'building-meese-rs',
      type: 'devlog',
      title: 'Building the first version of meese.rs',
      description: 'Initial architecture choices and tradeoffs for a static MDX writing system — why Astro, why Pagefind, and what I deliberately left out.',
      date: '2026-06-11', readingTime: '9 min',
      topics: ['static-sites', 'astro', 'publishing'],
      tags: ['mdx', 'pagefind', 'cloudflare-pages'],
      featured: true,
    },
    {
      slug: 'local-llms-benchmark',
      type: 'lab',
      title: 'Benchmarking local LLMs for task-specific code edits',
      description: 'A reproducible run comparing four quantized models on a fixed set of refactors. Numbers, prompts, and the harness are all here.',
      date: '2026-06-04', readingTime: '12 min',
      topics: ['local-llms', 'ai-devtools'],
      tags: ['benchmark', 'ollama', 'quantization'],
    },
    {
      slug: 'static-search-tradeoffs',
      type: 'essay',
      title: 'Static search is a tradeoff, not a downgrade',
      description: 'Why I shipped a build-time index instead of a search backend, and where that decision will eventually hurt.',
      date: '2026-05-29', readingTime: '6 min',
      topics: ['static-sites', 'search'],
      tags: ['pagefind', 'architecture'],
    },
    {
      slug: 'backlinks-at-build-time',
      type: 'reference',
      title: 'Generating backlinks at build time',
      description: 'A durable explainer of the backlink pass: frontmatter relations, internal links, and shared topics resolved into one graph.',
      date: '2026-05-22', readingTime: '5 min',
      topics: ['static-sites', 'publishing'],
      tags: ['mdx', 'graph'],
    },
    {
      slug: 'eas-build-cache',
      type: 'note',
      title: 'EAS build cache saved me an hour today',
      description: 'A short note on a cache flag that turned a 14-minute build into 90 seconds. Wish I had found it sooner.',
      date: '2026-05-18', readingTime: '2 min',
      topics: ['expo', 'mobile-dev'],
      tags: ['eas', 'ci'],
    },
    {
      slug: 'cursor-vs-claude-code',
      type: 'devlog',
      title: 'A week of pairing: Cursor vs Claude Code on the same repo',
      description: 'Same tasks, two tools, one codebase. Where each one pulled ahead and where both fell down on a real migration.',
      date: '2026-05-12', readingTime: '8 min',
      topics: ['ai-devtools', 'developer-experience'],
      tags: ['cursor', 'claude-code'],
    },
    {
      slug: 'review-bun-1-2',
      type: 'review',
      title: 'Bun v1.2',
      subject: 'Bun',
      version: 'v1.2',
      description: 'A genuinely fast all-in-one runtime that collapses three tools into one — with a few rough edges you will still feel in production.',
      date: '2026-06-10', readingTime: '11 min',
      topics: ['runtime', 'javascript', 'devtools'],
      tags: ['bun', 'nodejs', 'tooling'],
      featured: true,
    },
    {
      slug: 'review-claude-code',
      type: 'review',
      title: 'Everything Claude Code',
      subject: 'Claude Code',
      version: 'v2',
      description: 'The terminal-native coding agent that actually ships work — once you learn to scope it.',
      date: '2026-05-26', readingTime: '14 min',
      topics: ['ai-devtools', 'agents', 'developer-experience'],
      tags: ['claude-code', 'agents', 'cli'],
      featured: true,
    },
    {
      slug: 'review-paseo',
      type: 'review',
      title: 'Paseo',
      subject: 'Paseo',
      version: 'preview',
      description: 'One self-hosted interface for running Claude Code, Codex, Copilot and other coding agents in parallel — ambitious, and early.',
      date: '2026-06-12', readingTime: '8 min',
      topics: ['ai-devtools', 'agents', 'developer-experience'],
      tags: ['paseo', 'agents', 'self-hosted'],
      featured: true,
    },
  ];

  // Full review records (keyed by slug) for the review reading page
  const REVIEWS = {
    'review-claude-code': {
      subject: 'Claude Code',
      version: 'v2',
      tagline: 'A terminal-native AI coding agent that plans, edits across files, and runs your toolchain.',
      score: 4.6,
      verdict: 'recommended',
      verdictLabel: 'Recommended',
      reviewed: '2026-05-26',
      meta: [
        ['pricing', 'usage-based'],
        ['runs in', 'terminal'],
        ['first reviewed', '2026-02'],
        ['tested on', 'macOS · Linux'],
      ],
      links: [['repo', 'anthropics/claude-code'], ['docs', 'docs.claude.com']],
      criteria: [
        ['Autonomy', 4.7, 'Takes a vague task a long way before it needs you. The further it goes, the more scoping matters.'],
        ['Output quality', 4.6, 'Edits stay coherent across files and it cleans up after itself more than most tools do.'],
        ['Steerability', 4.5, 'Responds well to a tight spec and an AGENTS.md; flails on ambiguous ones.'],
        ['Cost control', 4.0, 'Usage-based pricing rewards good scoping and quietly punishes letting it wander.'],
        ['Ecosystem', 4.2, 'MCP, hooks, and skills make it composable; the surface area is still growing fast.'],
      ],
      pros: [
        'Genuinely ships multi-file work, not just snippets',
        'Composable via MCP, hooks, and skills',
        'Stays in the terminal where the tools already are',
        'Reads a repo carefully before it touches anything',
      ],
      cons: [
        'Costs scale with how loosely you scope it',
        'Long autonomous runs need review discipline',
        'Moves fast — workflows shift between versions',
        'Still rewards users who write good specs',
      ],
      body: [
        ['The pitch', 'Claude Code lives in your terminal and treats the whole repo as context. Give it a scoped task and it plans, edits across files, runs your tests, and iterates — closer to a junior engineer than an autocomplete.'],
        ['Where it shines', 'Migrations, refactors, and "wire this up end-to-end" tasks where the win is coordination across many files. An `AGENTS.md` and a tight prompt turn it from impressive to dependable.'],
        ['Where it bites', 'Hand it something vague and it will confidently go too far. The skill here is scoping and review, not prompting tricks — budget for both.'],
      ],
      bottomLine: 'The strongest terminal coding agent I have used. Treat it like a fast junior who needs a clear spec and a code review and it pays for itself; let it wander and it will cost you in tokens and cleanup.',
    },
    'review-bun-1-2': {
      subject: 'Bun',
      version: 'v1.2',
      tagline: 'The all-in-one JavaScript runtime, bundler, test runner, and package manager.',
      score: 4.2,
      verdict: 'caveats',
      verdictLabel: 'Recommended with caveats',
      reviewed: '2026-06-10',
      meta: [
        ['license', 'MIT'],
        ['written in', 'Zig'],
        ['first reviewed', '2025-11'],
        ['tested on', 'macOS · Linux'],
      ],
      links: [['repo', 'oven-sh/bun'], ['docs', 'bun.sh/docs']],
      criteria: [
        ['Performance', 4.8, 'Cold starts and install times are in a different class. This is the headline, and it delivers.'],
        ['Developer experience', 4.5, 'One binary for run/test/bundle/install. The ergonomics are excellent once it is in your hands.'],
        ['Node compatibility', 3.8, 'Most things work. The 5% that does not tends to surface late, in a dependency you did not write.'],
        ['Ecosystem & tooling', 3.5, 'Growing fast, but CI images, hosts, and observability still assume Node first.'],
        ['Stability', 3.5, 'Far steadier than a year ago. I would still pin versions and read the changelog before upgrading.'],
      ],
      pros: [
        'Install and test times that genuinely change your loop',
        'One tool replaces npm + tsx + jest + esbuild',
        'Native TypeScript and JSX with no config',
        'Drop-in for most Node scripts and servers',
      ],
      cons: [
        'Edge-case Node API gaps appear in transitive deps',
        'Some hosts / CI runners still need manual setup',
        'Smaller plugin ecosystem than the Node incumbents',
        'Moves fast — minor versions can shift behavior',
      ],
      body: [
        ['The pitch', 'Bun wants to be the only tool in your JavaScript toolchain, and for the common path it actually is. `bun install` is fast enough that you stop tabbing away to wait, and `bun test` runs a real suite in the time the Node equivalent spends booting.'],
        ['Where it shines', 'Greenfield services, scripts, and CI install steps are the sweet spot. If your dependency tree is mainstream, you get the speed with none of the pain, and the single-binary story removes a surprising amount of config.'],
        ['Where it bites', 'The failure mode is specific: a transitive dependency reaches for a Node API that Bun implements slightly differently, and you debug someone else’s code. It is rarer than it used to be, but it is the reason this is a four-star tool and not a five.'],
      ],
      bottomLine: 'If you are starting something new, reach for Bun and enjoy the speed. If you are migrating a large, mature Node service, pilot it on a non-critical path first — the wins are real, but so is the long tail of compatibility.',
    },
    'review-paseo': {
      subject: 'Paseo',
      version: 'preview',
      tagline: 'One self-hosted interface for running Claude Code, Codex, Copilot, OpenCode, and Pi agents in parallel.',
      score: 3.9,
      verdict: 'watch',
      verdictLabel: 'One to watch',
      reviewed: '2026-06-12',
      meta: [
        ['license', 'AGPL-3.0'],
        ['runs', 'self-hosted daemon'],
        ['clients', 'iOS · Android · desktop · CLI'],
        ['maintainer', 'solo'],
      ],
      links: [['repo', 'getpaseo/paseo'], ['docs', 'paseo.sh/docs']],
      criteria: [
        ['Multi-provider', 4.5, 'Claude Code, Codex, Copilot, OpenCode, and Pi behind one interface — pick the right model per job.'],
        ['Cross-device', 4.4, 'Start at your desk, check in from your phone, script it from the terminal. The handoff is the point.'],
        ['Privacy & control', 4.3, 'Self-hosted on your own machine with your configs; no telemetry, no forced logins.'],
        ['Maturity', 3.0, 'Young and moving fast. Capable, but expect rough edges and breaking changes.'],
        ['Docs & support', 3.2, 'Solo maintainer; Discord is faster than Issues. Docs cover the happy path.'],
      ],
      pros: [
        'One interface across five agent providers',
        'Self-hosted — your machine, your tools, your configs',
        'Genuinely cross-device, including a real mobile client',
        'Privacy-first: no telemetry, no forced login',
        'Orchestration skills: handoff, loop, advisor, committee',
      ],
      cons: [
        'Early and fast-moving; expect breaking changes',
        'Solo maintainer — Issues can lag behind Discord',
        'AGPL-3.0 will not suit every team or product',
        'You still install and configure each agent CLI yourself',
      ],
      body: [
        ['The pitch', 'Paseo is a self-hosted daemon that runs your coding agents and exposes them through one interface — desktop, mobile, web, or CLI. Run several in parallel, hand work between them, and drive it all from wherever you are.'],
        ['Where it shines', 'If you already live across Claude Code, Codex, and Copilot, Paseo collapses them into one control surface and lets you start a task at your desk and check it from your phone. The orchestration skills — handoff, loop, committee — are the genuinely novel part.'],
        ['Where it bites', 'It is early and maintained by one person. The ideas are ahead of the polish, and AGPL-3.0 plus self-hosting means it is not a drop-in for every team. Watch it; do not yet bet a critical workflow on it.'],
      ],
      bottomLine: 'The most interesting take on multi-agent orchestration I have tried, and the cross-device story is real. It is early and solo-maintained, so treat it as a promising daily-driver-in-waiting: run it, follow it, and revisit at a stable release.',
    },
  };

  // Per-post article bodies (block format) for the reading page.
  // Block forms: ['h',text] ['p',html] ['code',text] ['quote',text]
  //   ['callout',type,title,text] ['figure',caption,kind] ['ul',[items]] ['table',[[head],...rows]]
  const BODIES = {
    'expo-sdk-56-real-device': [
      ['p', "I had an Expo app that hadn't been touched in two years. Getting it onto a real Pixel under SDK 56 should have been a fifteen-minute job — it was not, but the friction was all in places the docs describe separately and never connect."],
      ['h', 'The setup'],
      ['p', "Start from a clean upgrade. Bump the SDK, let the CLI rewrite the config, and resist the urge to fix lint noise before the thing even boots."],
      ['code', "npx expo install expo@^56.0.0\nnpx expo-doctor\neas build --profile development --platform android"],
      ['callout', 'warning', 'Watch for SDK / runtime mismatch', "Expo Go may not support the newest SDK immediately depending on release timing. If the splash screen hangs, this is almost always why — not your code."],
      ['h', 'Build a dev client, not Expo Go'],
      ['p', "A development build pins the native runtime to **your** SDK, which removes the entire class of mismatch. It costs one EAS build up front and pays for itself the first time you'd otherwise chase a phantom error."],
      ['figure', 'The dev-client install flow on a physical device — QR pairing, then the dev server on the same network.', 'screenshot'],
      ['h', 'Takeaways'],
      ['ul', ['Use a dev client over Expo Go for bleeding-edge SDKs', 'Read errors one layer up from where they point', 'Keep the first upgrade commit boring']],
    ],
    'expo-go-version-mismatch': [
      ['p', "The failure mode is genuinely bad: the error names the **runtime** when the real mismatch is the **SDK**. You'll burn a few minutes looking in the wrong layer."],
      ['callout', 'note', 'The one-line fix', "Stop using Expo Go for a bleeding-edge SDK. A dev client pins the runtime to your SDK and the whole error class disappears."],
      ['quote', "If the tool can detect the mismatch well enough to error, it can detect it well enough to tell you which side is wrong."],
    ],
    'building-meese-rs': [
      ['p', "This site is a deliberate exercise in restraint: static-first, no server runtime, and as few moving parts as I could get away with. Here's the shape of v0 and the tradeoffs behind it."],
      ['h', 'The stack'],
      ['p', "Astro for content collections, MDX for authoring, Pagefind for search, Cloudflare Pages for hosting. Everything that can be computed at build time is."],
      ['code', "astro build && pagefind --site dist"],
      ['h', 'What I left out, on purpose'],
      ['table', [['Feature', 'Decision'], ['Comments', 'Out — no moderation surface'], ['CMS', 'Out — content is MDX in the repo'], ['Runtime search', 'Out — static index instead']]],
      ['figure', 'The build pipeline: content collection → static HTML → Pagefind index → graph.json.', 'diagram'],
      ['p', "The result is a site I can publish from a laptop and forget about until I have something to write."],
    ],
    'local-llms-benchmark': [
      ['p', "A reproducible run comparing four quantized models on a fixed set of refactors. Same prompts, same harness, same machine — here are the numbers."],
      ['h', 'Results'],
      ['table', [['Model', 'Pass rate', 'Median latency'], ['Q4_K_M · 7B', '68%', '4.1s'], ['Q5_K_M · 7B', '72%', '5.8s'], ['Q4 · 14B', '81%', '9.2s'], ['Q4 · 32B', '88%', '18.6s']]],
      ['callout', 'context', 'How to read this', "Pass rate is against a fixed acceptance test per task. Latency is wall-clock on a single consumer GPU; your numbers will move with hardware."],
      ['figure', 'Pass rate vs. latency across the four quantizations — the 14B sits on the efficient frontier.', 'chart'],
      ['p', "The 14B at Q4 was the sweet spot for my hardware: most of the quality of the 32B at half the latency."],
    ],
    'static-search-tradeoffs': [
      ['p', "I shipped a build-time search index instead of a search backend. That's a tradeoff, not a downgrade — and it's worth being honest about where it will eventually hurt."],
      ['quote', "Static search is the right default until your corpus or your query patterns outgrow it. Most sites never do."],
      ['h', 'Where it pays off'],
      ['p', "No server to run, no index to keep warm, no query that can take the site down. The index ships with the deploy and works offline."],
      ['h', 'Where it will bite'],
      ['p', "Large corpora and faceted, frequently-changing data are the failure cases. When I hit them, I'll add a backend for search alone and keep the reading path static."],
    ],
    'backlinks-at-build-time': [
      ['p', "Backlinks are generated at build time from four sources: manual frontmatter relations, internal links, supersedes/supersededBy fields, and shared topics."],
      ['code', "const edges = posts.flatMap(p => [\n  ...p.related.map(r => link(p, r)),\n  ...internalLinks(p),\n]);"],
      ['ul', ['Manual related links first', 'Direct internal-link backlinks second', 'Then “more in this topic”']],
      ['callout', 'tip', 'Keep it useful, not exhaustive', "A backlink section that lists everything is noise. Cap it, rank it, and let the graph page handle full discovery."],
    ],
    'eas-build-cache': [
      ['p', "A cache flag turned a 14-minute rebuild into 90 seconds. Filing this so future-me finds it faster than I did."],
      ['code', "eas build --profile development --platform android --clear-cache=false"],
      ['p', "Obvious in hindsight; invisible in the docs at the moment I needed it."],
    ],
    'cursor-vs-claude-code': [
      ['p', "Same tasks, two tools, one codebase, one week. I ran a real migration through both and kept score on the parts that actually matter day to day."],
      ['h', 'The scorecard'],
      ['table', [['Dimension', 'Cursor', 'Claude Code'], ['In-editor flow', 'Strong', '—'], ['Whole-repo tasks', 'Good', 'Strong'], ['Autonomy', 'Medium', 'High'], ['Reviewability', 'High', 'Medium']]],
      ['p', "Neither won outright. Cursor stayed ahead for tight in-editor edits; Claude Code pulled away on multi-file, run-the-tools work."],
      ['callout', 'context', 'My takeaway', "I keep both. Cursor for surgical edits in the editor, Claude Code in the terminal for coordinated, multi-file changes."],
    ],
  };




  const TOPICS = [
    { slug: 'react-native', label: 'react-native', count: 6, hue: 'var(--hue-cyan)' },
    { slug: 'ai-devtools', label: 'ai-devtools', count: 5, hue: 'var(--hue-violet)' },
    { slug: 'static-sites', label: 'static-sites', count: 4, hue: 'var(--hue-green)' },
    { slug: 'local-llms', label: 'local-llms', count: 3, hue: 'var(--hue-gold)' },
    { slug: 'expo', label: 'expo', count: 5, hue: 'var(--hue-cyan)' },
    { slug: 'developer-experience', label: 'developer-experience', count: 4, hue: 'var(--hue-rose)' },
    { slug: 'publishing', label: 'publishing', count: 3, hue: 'var(--hue-slate)' },
    { slug: 'security', label: 'security', count: 2, hue: 'var(--hue-gold)' },
  ];

  // Concept graph: posts + topics, edges by topic membership
  const TYPE_HUE = {
    guide: 'var(--hue-cyan)', note: 'var(--hue-slate)', devlog: 'var(--hue-green)',
    essay: 'var(--hue-violet)', lab: 'var(--hue-gold)', reference: 'var(--hue-rose)',
    topic: 'var(--accent)',
  };

  // hand-placed positions (0..1) for a sleek, legible layout
  const GRAPH = {
    nodes: [
      { id: 't:react-native', kind: 'topic', label: 'react-native', x: 0.20, y: 0.30, r: 17 },
      { id: 't:static-sites', kind: 'topic', label: 'static-sites', x: 0.72, y: 0.32, r: 16 },
      { id: 't:ai-devtools', kind: 'topic', label: 'ai-devtools', x: 0.50, y: 0.72, r: 16 },
      { id: 't:expo', kind: 'topic', label: 'expo', x: 0.30, y: 0.58, r: 13 },
      { id: 'expo-sdk-56-real-device', kind: 'guide', label: 'Expo SDK 56 on device', x: 0.12, y: 0.16, r: 9 },
      { id: 'expo-go-version-mismatch', kind: 'note', label: 'Expo Go mismatch', x: 0.40, y: 0.16, r: 7 },
      { id: 'eas-build-cache', kind: 'note', label: 'EAS build cache', x: 0.16, y: 0.48, r: 7 },
      { id: 'building-meese-rs', kind: 'devlog', label: 'Building meese.rs', x: 0.84, y: 0.18, r: 9 },
      { id: 'static-search-tradeoffs', kind: 'essay', label: 'Static search', x: 0.88, y: 0.48, r: 8 },
      { id: 'backlinks-at-build-time', kind: 'reference', label: 'Backlinks pass', x: 0.66, y: 0.52, r: 8 },
      { id: 'local-llms-benchmark', kind: 'lab', label: 'Local LLM bench', x: 0.40, y: 0.88, r: 9 },
      { id: 'cursor-vs-claude-code', kind: 'devlog', label: 'Cursor vs Claude', x: 0.66, y: 0.86, r: 8 },
    ],
    edges: [
      ['expo-sdk-56-real-device', 't:react-native'], ['expo-sdk-56-real-device', 't:expo'],
      ['expo-go-version-mismatch', 't:react-native'], ['expo-go-version-mismatch', 't:expo'],
      ['eas-build-cache', 't:expo'], ['t:expo', 't:react-native'],
      ['building-meese-rs', 't:static-sites'], ['static-search-tradeoffs', 't:static-sites'],
      ['backlinks-at-build-time', 't:static-sites'], ['local-llms-benchmark', 't:ai-devtools'],
      ['cursor-vs-claude-code', 't:ai-devtools'], ['building-meese-rs', 't:ai-devtools'],
      ['static-search-tradeoffs', 't:ai-devtools'],
    ],
  };

  window.KIT_DATA = { POSTS, TOPICS, GRAPH, TYPE_HUE, REVIEWS, BODIES };
})();
